{{- define "siglens.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
data:
  server.yaml: |-
    {{- .config | toYaml | nindent 4 }}
    ingestNode: {{ .isIngestNode }}
    queryNode: {{ .isQueryNode }}
    etcd:
      enabled: {{ .multinode.enabled }}
      username: {{ .siglensEtcd.username }}
      password: {{ .siglensEtcd.password | default .etcdRootPassword }}
      seedUrls:
        - {{ printf "http://%s-etcd.%s.svc.cluster.local:2379" .Release.Name .namespace }}
{{- end -}}

{{- if .Values.multinode.enabled }}
  {{- $ingestConfigmap := dict
    "Release" .Release
    "multinode" .Values.multinode
    "name" (printf "%s-ingest-configmap" .Release.Name)
    "namespace" .Values.namespace
    "config" .Values.config
    "siglensEtcd" .Values.siglensEtcdOverrides
    "etcdRootPassword" .Values.etcd.auth.rbac.rootPassword
    "isIngestNode" true
    "isQueryNode" (not .Values.multinode.enabled)
  }}
  {{- $queryConfigmap := dict
    "Release" .Release
    "multinode" .Values.multinode
    "name" (printf "%s-query-configmap" .Release.Name)
    "namespace" .Values.namespace
    "config" .Values.config
    "siglensEtcd" .Values.siglensEtcdOverrides
    "etcdRootPassword" .Values.etcd.auth.rbac.rootPassword
    "isIngestNode" (not .Values.multinode.enabled)
    "isQueryNode" true
  }}

  {{- include "siglens.configmap" $ingestConfigmap -}}
  {{ printf "\n---\n" }}
  {{- include "siglens.configmap" $queryConfigmap -}}
{{ else }}
  {{- $configmap := dict
    "Release" .Release
    "multinode" .Values.multinode
    "name" (printf "%s-%s" .Release.Name "ingest-and-query-configmap")
    "namespace" .Values.namespace
    "config" .Values.config
    "siglensEtcd" .Values.siglensEtcdOverrides
    "etcdRootPassword" .Values.etcd.auth.rbac.rootPassword
    "isIngestNode" true
    "isQueryNode" true
  }}

  {{- include "siglens.configmap" $configmap -}}
{{- end -}}
