{{- if .Values.registry.dockerConfigBase64 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-registry-secret
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry.dockerConfigBase64 }}
{{- end }}
