apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingest-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.ingestService.selector.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.ingestService.port }}
      targetPort: {{ .Values.ingestService.targetPort }}
  type: LoadBalancer