apiVersion: v1
kind: Service
metadata:
  name: ingest-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.ingestService.selector.app }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
