apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- if and .Values.config.tls.enabled .Values.ingress.certManagerIssuer }}
    cert-manager.io/issuer: "{{ .Values.ingress.certManagerIssuer }}"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.config.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.queryHost }}
    - {{ .Values.ingestHost }}
    - {{ .Values.managementHost }}
    secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
  rules:
  - host: {{ .Values.queryHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-query-service
            port:
              number: {{ .Values.config.queryPort }}
  - host: {{ .Values.ingestHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-ingest-service
            port:
              number: {{ .Values.config.ingestPort }}
  - host: {{ .Values.managementHost}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-management-service
            port:
              number: {{ .Values.config.managementPort }}
