apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-management-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.managementService.selector.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.managementService.port }}
      targetPort: {{ .Values.managementService.targetPort }}
  type: LoadBalancer
