apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-query-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.queryService.selector.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.queryService.port }}
      targetPort: {{ .Values.queryService.targetPort }}
  type: LoadBalancer