apiVersion: v1
kind: Service
metadata:
  name: query-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.queryService.selector.app }}
  ports:
    - protocol: TCP
      port: 5122
      targetPort: 5122
  type: LoadBalancer
