apiVersion: v1
kind: Service
metadata:
  name: raft-service
  namespace: {{ .Values.global.namespace }}
spec:
  clusterIP: None
  selector:
    app: raft-node
  ports:
    - port: 2379
      targetPort: 2379
