apiVersion: v1
kind: Service
metadata:
  name: raft-service
  namespace: {{ .Values.global.namespace }}
spec:
  clusterIP: None
  selector:
    app: raft-node
  ports:
    - port: {{ .Values.raft.deployment.ports.raft }}
      targetPort: {{ .Values.raft.deployment.ports.raft }}
