apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: raft-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.raft.deployment.replicas }}
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi  # Adjust the storage size as necessary
  selector:
    matchLabels:
      app: raft-node
  template:
    metadata:
      labels:
        app: raft-node
      annotations:
        checksum/config: sha256-checksum-placeholder
    spec:
      serviceAccountName: {{ .Release.Name }}-service-account
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 1000:1000 /siglens/data']
        volumeMounts:
        - name: data-volume
          mountPath: /siglens/data
      containers:
      - name: raft-container
        image: {{ .Values.raft.deployment.image }}
        imagePullPolicy: {{ .Values.raft.deployment.imagePullPolicy }}
        command: ["/siglens/sigscalr"]
        args:
          - /siglens/sigscalr
          - --config
          - /config/server.yaml
        ports:
        - containerPort: 8081
        - containerPort: 2379  # Raft port
        volumeMounts:
        - mountPath: /siglens/data
          name: data-volume
        - mountPath: /config
          name: raft-config
        - mountPath: /license
          name: license-volume
        - mountPath: /certs
          name: cert-volume
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: gcp-pd-pvc
      - name: raft-config
        configMap:
          name: raft-configmap
      - name: license-volume
        secret:
          secretName: {{ .Release.Name }}-license-secret
          items:
          - key: license
            path: license.txt
      - name: cert-volume
        secret:
          secretName: ingress-tls
