apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-service-account
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- range $key, $value := .Values.serviceAccountAnnotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
