apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-configmap
  namespace: {{ .Values.global.namespace }}
data:
  server.yaml: |-
    tls:
      enabled: {{ .Values.config.tls.enabled }}
      certificatePath: {{ .Values.config.tls.certificatePath }}
      privateKeyPath: {{ .Values.config.tls.privateKeyPath }}
    ingestPort: {{ .Values.config.ingestPort }}
    queryPort: {{ .Values.config.queryPort }}
    dataPath: {{ .Values.config.dataPath }}
    timestampKey: {{ .Values.config.timestampKey }}
    licenseKeyPath: {{ .Values.config.licenseKeyPath }}
    ssInstanceName: {{ .Values.config.worker.ssInstanceName }}
    rbac:
      provider: sqlite
      dbname: db1
    ingestNode: true
    queryNode: true
    etcd:
      enabled: true
      username: root
      password: dontkeepthispassword
      seedUrls:
        - {{ printf "http://%s-etcd.%s.svc.cluster.local:2379" .Release.Name .namespace }}
    raft:
      enabled: false