apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-configmap
  namespace: {{ .Values.global.namespace }}
data:
  server.yaml: |-
    {{ toYaml .Values.config | nindent 4 }}
    ingestNode: true
    queryNode: true
    isManagementNode: true
    isRaftNode: false
    queryHostname: {{ .Values.queryHostWithPort }}
    ingestUrl: {{ .Values.ingestHost }}
    raft:
      raftNodes:
{{- $namespace := .Release.Namespace }}
{{- range $i := until (int .Values.raft.deployment.replicas) }}
        - {{ printf "http://raft-deployment-%d.raft-service.%s.svc.cluster.local:2379" $i $namespace }}
{{- end }}
