{{- if .Values.siglens.otel.service.serviceType -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "siglens.fullname" . }}-metrics-otel-collector
  namespace: {{ .Release.Namespace }}
  labels:
      {{ include "siglens-server.labels" . | nindent 4 }}
  
spec:
  type: {{ .Values.siglens.otel.service.serviceType }}
  ports:
    - port: {{ .Values.siglens.otel.service.port }}
      targetPort: otelport
      protocol: TCP
      name: otel-http

  selector:
    {{- include "siglens-server.selectorLabels" . | nindent 4 -}}
{{- end -}}
